{
 "title": "Critic",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Service Status",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by(name) (critic_target_is_healthy)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": " TLS Cert Expires in",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(max by (name) (critic_target_server_certificate_expiration_time)-time())/(3600*24)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Probe Request Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by(name) (critic_target_request_duration)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Probe History",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max by (name) (critic_target_is_healthy)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}