{
 "title": "Docker Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Cumulative CPU Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "%" }
   ],
   "targets": [
    {
     "expr": "sum(max by (name) (rate(container_cpu_usage_seconds_total{name =~ \".+\"}[5m])))*100",
     "legendFormat": "% CPU used by all containers"
    }
   ]
  },
  {
   "title": "Cumulative Memory Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum( max by (name) (container_memory_usage_bytes{name=~\".+\"}))",
     "legendFormat": "Total Memory used by all containers"
    }
   ]
  },
  {
   "title": "CPU Use Pie Chart",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 8 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by (name) (rate(container_cpu_usage_seconds_total{name=~\".+\"}[5m])*100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Use Pie Chart",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max by (name) (container_memory_usage_bytes{name=~\".+\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Use per Container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (name) (rate(container_cpu_usage_seconds_total{name =~ \".+\"}[5m])*100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Use per Container",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (name) (container_memory_usage_bytes{name =~ \".+\"})",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}