{
 "title": "Docker Container Details",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Container Name",
    "query": "label_values(container_last_seen, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "cpu %" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_usage_seconds_total{name=\"$container_name\"}[5m])*100)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max by (name) (container_memory_usage_bytes{name=\"$container_name\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "max by (name) (container_memory_rss{name=\"$container_name\"})",
     "legendFormat": "RSS"
    },
    {
     "expr": "max by (name) (container_memory_swap{name=\"$container_name\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "max by (container_name) (go_memstats_heap_alloc_bytes{container_name=\"$container_name\"})",
     "legendFormat": "Go Heap"
    },
    {
     "expr": "max by (container_name) (go_memstats_heap_inuse_bytes{container_name=\"$container_name\"})",
     "legendFormat": "Go Heap in Use"
    },
    {
     "expr": "max by (name) (container_spec_memory_limit_bytes{name = \"$container_name\"})",
     "legendFormat": "Container Limit"
    }
   ]
  },
  {
   "title": "Memory failures per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (name) (rate(container_memory_failures_total{name=\"$container_name\"}[5m]))",
     "legendFormat": "Memory failures per second"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (rate(container_network_receive_bytes_total{name=\"$container_name\"}[5m]))",
     "legendFormat": "Received Bytes/s"
    },
    {
     "expr": "sum by (name) (rate(container_network_transmit_bytes_total{name=\"$container_name\"}[5m]))",
     "legendFormat": "Sent Bytes/s"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "{container_name=\"$container_name\"}"
    }
   ]
  }
 ]
}