{
 "title": "Host",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Use",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 13, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100-node_memory_MemAvailable_bytes/node_memory_MemTotal_bytes*100",
     "legendFormat": "ram"
    },
    {
     "expr": "100-node_memory_SwapFree_bytes/node_memory_SwapTotal_bytes*100",
     "legendFormat": "swap"
    },
    {
     "expr": "(1-rate(node_cpu_seconds_total{mode = \"idle\"}[1m]))*100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "1/s" } },
   "yaxes": [
    { "format": "1/s" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu_seconds_total{mode != \"idle\"}[1m])",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "load1" },
    { "expr": "node_load5", "legendFormat": "load5" },
    { "expr": "node_load15", "legendFormat": "load15" }
   ]
  },
  {
   "title": "Disk R/W",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m])\n",
     "legendFormat": "Read: {{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "Writes {{device}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "-rate(node_network_receive_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!=\"lo\"}[1m])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}