{
 "title": "Traefik",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Requests per Second",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (entrypoint) (rate(traefik_entrypoint_requests_total{entrypoint != \"traefik\"}[1m]))",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "Open Connections per Service and Protocol",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (service, protocol) (traefik_service_open_connections)",
     "legendFormat": "{{service}}:{{protocol}}"
    }
   ]
  },
  {
   "title": "HTTP Request Status Codes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (code) (rate(traefik_service_requests_total[1m]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Open Connections by Entry Point",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (entrypoint) (traefik_entrypoint_open_connections{entrypoint != \"traefik\"})",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  }
 ]
}